baseURL = 'https://artizio.app/'
languageCode = 'en-us'
title = 'Artizio'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.googleAnalytics]
    id = 'G-G0BM8F9845'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false
    # anonymizeIP = true  # Uncomment if you want to anonymize IP addresses

[params]
  author = 'Ribicube LLC'
  description = 'Create coloring pages from photos, moods, or your imagination. Pick a style, color in-app, or print anytime. Perfect for mindful breaks, travel memories, and creative gifts.'
  show_reading_time = false
  recent_posts_number = 3
  background_color_class = 'artizio-gradient'
  custom_css = ['css/custom.css']
  site_logo = 'images/logo/artizio-logo.png'
  favicon = 'favicon.ico'

[params.ananke.social.follow]
  networks = ["instagram", "facebook"]

[params.ananke.social.share]
  icons = true # show icons for each share link
  sharetext = true # show the share text
  networks = [
    "email",
    "facebook",
    "linkedin",
    "x-twitter",
    "whatsapp"
  ]

[params.ananke.social.instagram]
  username = "artizioapp"

[params.ananke.social.facebook]
  profilelink = "https://www.facebook.com/profile.php?id=61578154805779"
  
[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  # [[menu.main]]
  #   identifier = 'terms'
  #   name = 'Terms'
  #   url = '/terms/'
  #   weight = 2
  # [[menu.main]]
  #   identifier = 'policy'
  #   name = 'Privacy Policy'
  #   url = '/policy/'
  #   weight = 3
  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '/contact/'
    weight = 4

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
